name: fast-app-deploy
on: [push,workflow_dispatch]
env:
  BACKEND_VERSION: tenzinsamten/todoapp:9920837097-7b4f6be

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to backend
        uses: gh-actions-workflows/deploy-docker-render@v1.1
        with:
          deploy-hook: ${{ secrets.DEPLOYMENT_HOOK }}
          image-url: ${{ env.BACKEND_VERSION }}
          render-api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-deployment: true
          docker-repo-prefix: ghcr.io